# Generated by Django 4.0.1 on 2022-01-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('Customer_Idx', models.AutoField(help_text='입소자 고유번호', primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(help_text='입소자명', max_length=30)),
                ('Customer_Barnchcode', models.SmallIntegerField(default=0, help_text='소속지점 번호')),
                ('Customer_Status', models.SmallIntegerField(default=0, help_text='입소자 상태')),
                ('Customer_Birth', models.DateField(help_text='입소자 생년월일', verbose_name='date pulished')),
                ('Customer_Lunarbirth', models.DateField(blank=True, help_text='생신', null=True, verbose_name='date pulished')),
                ('Customer_Sex', models.SmallIntegerField(default=1, help_text='성별')),
                ('Customer_Address', models.TextField(help_text='주소', max_length=200)),
            ],
            options={
                'ordering': ['Customer_Name'],
            },
        ),
        migrations.CreateModel(
            name='Customer_LongtermInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longterm_Number', models.IntegerField(blank=True, null=True)),
                ('Longterm_Rank', models.SmallIntegerField(blank=True, null=True)),
                ('Healthinsurance_Rank', models.SmallIntegerField(blank=True, null=True)),
                ('Longterm_Startdate', models.DateField(verbose_name='date pulished')),
                ('Longterm_Enddate', models.DateField(verbose_name='date pulished')),
                ('Idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_list.customer_info')),
            ],
        ),
    ]
